# Site wide configuration

title:            Branch 'n' Bound
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Satyajit Sarangi
  avatar: bio-photo.jpg
  bio: "I am a software engineer currently residing in Bay Area."
  email: kernel.saty@gmail.com
  disqus-shortname: ssarangi
  twitter: ssarangi
  facebook: #username
  google:
    plus: #username
    analytics: UA-21922961-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ssarangi
  stackoverflow: 1327837/ssarangi
  linkedin: satyajitsarangi
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
plugins_dir: _plugins


# Forked from https://github.com/jglovier/resume-template/blob/gh-pages/_config.yml
# Resume settings
resume_avatar:                  "false"
resume_name:                    "Satyajit Sarangi"
resume_title:                   "Software Engineer"
resume_contact_email:
  "satyajit.sarangi@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://ssarangi.github.io"

# Design settings
resume_theme:                   default